## PyTorch Tutorial

IFT6135 – Representation Learning

A Deep Learning Course, January 2019

By Chin-Wei Huang 

(Adapted from Sandeep Subramanian's MILA welcome tutorial)

## 1. Introduction to the torch tensor library
### Torch's numpy equivalent with GPU support

In [1]:
import numpy as np
from __future__ import print_function

In [2]:
import torch

### Initialize a random tensor

In [3]:
torch.Tensor(5, 3)

tensor([[ 0.0000e+00,  3.6893e+19,  0.0000e+00],
        [ 3.6893e+19,  2.4074e-35,  1.4013e-45],
        [ 3.4009e-35,  1.8367e-40,  2.0115e+18],
        [ 4.5821e-41,  2.4258e-35,  1.4013e-45],
        [-1.6533e-06,  2.5250e-29,  0.0000e+00]])

### From a uniform distribution

In [4]:
# intialization
print(torch.Tensor(5, 3).uniform_(-1, 1))
# sampling
print(torch.rand(5,3)*2-1)

tensor([[-0.1800,  0.8330, -0.6901],
        [ 0.2890,  0.3168, -0.6920],
        [-0.8239,  0.8455, -0.8767],
        [ 0.8772,  0.5026,  0.1646],
        [ 0.2608, -0.3901,  0.7063]])
tensor([[ 0.6121, -0.7246, -0.9442],
        [ 0.1773,  0.7809, -0.9708],
        [-0.3570,  0.8262, -0.2329],
        [-0.7994, -0.2972,  0.3238],
        [-0.7662, -0.6796,  0.1692]])


### Get it's shape

In [7]:
x = torch.Tensor(5, 3).uniform_(-1, 1)
print(x.size())

# or your favorite np_array.shape
print(x.shape)

# dimensionality of the 0'th axis?
# print(???)
print(x.size(0))
print(x.shape[0])

torch.Size([5, 3])
torch.Size([5, 3])
5
5


### Tensor Types
source: http://pytorch.org/docs/master/tensors.html

|Data type |Tensor|
|----------|------|
|32-bit floating point|	torch.FloatTensor|
|64-bit floating point|	torch.DoubleTensor|
|16-bit floating point|	torch.HalfTensor|
|8-bit integer (unsigned)|torch.ByteTensor|
|8-bit integer (signed)|torch.CharTensor|
|16-bit integer (signed)|torch.ShortTensor|
|32-bit integer (signed)|torch.IntTensor|
|64-bit integer (signed)|torch.LongTensor|

### Creation from lists & numpy

In [13]:
z = torch.LongTensor([[1, 3], [2, 9]])
print(z.type())
# Cast to numpy ndarray
print(z.numpy().dtype)
z_ = torch.LongTensor([[1, 3], [2, 9]])
z+z_

torch.LongTensor
int64


tensor([[  2,   6],
        [  4,  18]])

In [16]:
# Data type inferred from numpy
print(torch.from_numpy(np.random.rand(5, 3)).type())
print(torch.from_numpy(np.random.rand(5, 3).astype(np.float32)).type())
print(torch.from_numpy(np.random.rand(5, 3)).float().dtype)


torch.DoubleTensor
torch.FloatTensor
torch.float32


In [18]:
# examples of type error
a = torch.randn(1) # x ~ N(0,1)
b = torch.from_numpy(np.ones(1)).float()

x+b

tensor([[ 1.9335,  1.7467,  0.1057],
        [ 0.3516,  1.0909,  1.7426],
        [ 0.6338,  1.2330,  1.6327],
        [ 0.7595,  1.2103,  0.9412],
        [ 1.2295,  1.0834,  1.3096]])

### Simple mathematical operations

In [21]:
y = x ** torch.randn(5, 3)
print(y)

tensor([[ 0.9601,  1.6281,     nan],
        [    nan,  0.4508,  1.0954],
        [    nan,  5.1548,  1.1561],
        [    nan,  0.3945,     nan],
        [ 0.4676,  0.0382,  1.0491]])


In [23]:
noise = torch.randn(5, 3)
y = x / torch.sqrt(noise ** 2)
# equal to torch.abs
y_ = x / torch.abs(noise)

print(y)
print(y_)


tensor([[ 0.7650,  2.1209, -1.9414],
        [-0.9739,  0.4886,  4.6878],
        [-0.3125,  0.1874,  1.8736],
        [-0.1248,  0.0709, -0.0995],
        [ 0.1461,  0.0712,  0.3796]])
tensor([[ 0.7650,  2.1209, -1.9414],
        [-0.9739,  0.4886,  4.6878],
        [-0.3125,  0.1874,  1.8736],
        [-0.1248,  0.0709, -0.0995],
        [ 0.1461,  0.0712,  0.3796]])


### Broadcasting

In [27]:
print(x.size())
print(x)
#y = x + torch.arange(5).view(5,1)
y = x + torch.arange(3)
print(y)
# print(x + torch.arange(5))

torch.Size([5, 3])
tensor([[ 0.9335,  0.7467, -0.8943],
        [-0.6484,  0.0909,  0.7426],
        [-0.3662,  0.2330,  0.6327],
        [-0.2405,  0.2103, -0.0588],
        [ 0.2295,  0.0834,  0.3096]])
tensor([[ 0.9335,  1.7467,  1.1057],
        [-0.6484,  1.0909,  2.7426],
        [-0.3662,  1.2330,  2.6327],
        [-0.2405,  1.2103,  1.9412],
        [ 0.2295,  1.0834,  2.3096]])


### Reshape

In [38]:
y = torch.randn(5, 10, 15)
print(y.size())
print(y.view(-1, 15).size())  # Same as doing y.view(50, 15)
print(y.view(-1, 15).unsqueeze(1).size()) # Adds a dimension at index 1.
print(y.view(-1, 15).unsqueeze(1).unsqueeze(2).unsqueeze(3).squeeze().size())
# If input is of shape: (Ax1xBxCx1xD)(Ax1xBxCx1xD) then the out Tensor will be of shape: (AxBxCxD)(AxBxCxD)
print()
print(y.transpose(0, 1).size())
print(y.transpose(1, 2).size())
print(y.transpose(0, 1).transpose(1, 2).size())
print(y.permute(1, 2, 0).size())

torch.Size([5, 10, 15])
torch.Size([50, 15])
torch.Size([50, 1, 15])
torch.Size([50, 15])

torch.Size([10, 5, 15])
torch.Size([5, 15, 10])
torch.Size([10, 15, 5])
torch.Size([10, 15, 5])


### Repeat

In [41]:
print(y.view(-1, 15).unsqueeze(1).expand(50, 100, 15).size())
print(y.view(-1, 15).unsqueeze(1).expand_as(torch.randn(50, 100, 15)).size())
# don't confuse it with tensor.repeat ...
print(y.view(-1, 15).unsqueeze(1).repeat(50,100,1).size())

torch.Size([50, 100, 15])
torch.Size([50, 100, 15])
torch.Size([2500, 100, 15])


### Concatenate

In [47]:
# 2 is the dimension over which the tensors are concatenated
print(torch.cat([y, y], 2).size())
# stack concatenates the sequence of tensors along a new dimension.
print(torch.stack([y, y], 0).size())

# Q: how to do tensor.stack using cat?
print(torch.cat([y[None], y[None]], 0).size())

torch.Size([5, 10, 30])
torch.Size([2, 5, 10, 15])
torch.Size([2, 5, 10, 15])


### Advanced Indexing

In [61]:
y = torch.randn(2, 3, 4)
print(y[[1, 0, 1, 1]].size())

# PyTorch doesn't support negative strides yet so ::-1 does not work.
rev_idx = torch.arange(1, -1, -1).long()
print(rev_idx)
print(y[rev_idx].size())


# gather(input, dim, index)
v = torch.arange(12).view(3,4)
print(v.shape)
print(v)
# [0,1,2,3]
# [4,5,6,7]
# [8,9,10,11]
# want to return [1,6,8]

print(torch.gather(v, 1, torch.tensor([1,2,0]).long().unsqueeze(1)))


torch.Size([4, 3, 4])
tensor([ 1,  0])
torch.Size([2, 3, 4])
torch.Size([3, 4])
tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.]])
tensor([[ 1.],
        [ 6.],
        [ 8.]])


### GPU support

In [16]:
x = torch.cuda.HalfTensor(5, 3).uniform_(-1, 1)
y = torch.cuda.HalfTensor(3, 5).uniform_(-1, 1)
torch.matmul(x, y)


 0.2456  1.1543  0.5376  0.4358 -0.0369
 0.8247 -0.4143 -0.7188  0.3953  0.2573
-0.1346  0.7329  0.5156  0.0864 -0.1349
-0.3555  0.3135  0.3921 -0.1428 -0.1368
-0.4385  0.5601  0.6533 -0.2793 -0.5220
[torch.cuda.HalfTensor of size 5x5 (GPU 0)]

### Move tensors on the CPU -> GPU

In [17]:
x = torch.FloatTensor(5, 3).uniform_(-1, 1)
print(x)
x = x.cuda(device=0)
print(x)
x = x.cpu()
print(x)


-0.3758 -0.1090  0.7911
 0.2839 -0.9136  0.1070
 0.9184  0.5113 -0.8040
-0.3412 -0.8895 -0.5780
-0.0992  0.0983  0.6074
[torch.FloatTensor of size 5x3]


-0.3758 -0.1090  0.7911
 0.2839 -0.9136  0.1070
 0.9184  0.5113 -0.8040
-0.3412 -0.8895 -0.5780
-0.0992  0.0983  0.6074
[torch.cuda.FloatTensor of size 5x3 (GPU 0)]


-0.3758 -0.1090  0.7911
 0.2839 -0.9136  0.1070
 0.9184  0.5113 -0.8040
-0.3412 -0.8895 -0.5780
-0.0992  0.0983  0.6074
[torch.FloatTensor of size 5x3]



### Contiguity in memory

In [67]:
x = torch.FloatTensor(5, 3).uniform_(-1, 1)
print(x)
#x = x.cuda(device=0)
print(x)
print('Contiguity : %s ' % (x.is_contiguous()))
x = x.unsqueeze(0).expand(30, 5, 3)
print('Contiguity : %s ' % (x.is_contiguous()))
x = x.contiguous()
print('Contiguity : %s ' % (x.is_contiguous()))



tensor([[ 0.9361,  0.5925, -0.3561],
        [-0.2556, -0.8500,  0.6730],
        [ 0.8848, -0.4681,  0.7800],
        [ 0.5135, -0.4303, -0.7775],
        [ 0.0840, -0.3217, -0.7249]])
tensor([[ 0.9361,  0.5925, -0.3561],
        [-0.2556, -0.8500,  0.6730],
        [ 0.8848, -0.4681,  0.7800],
        [ 0.5135, -0.4303, -0.7775],
        [ 0.0840, -0.3217, -0.7249]])
Contiguity : True 
Contiguity : False 
Contiguity : True 
